### Mock OData V2
GET http://localhost:4005/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$top=10
    &$inlinecount=allpages
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked
    #&$filter=Customer ne ''
    #&$filter=BusinessPartner eq '1000038'
Accept: application/json
### 
GET http://localhost:4005/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_CustomerSalesAreaText
    ?$top=10
    &$inlinecount=allpages
Accept: application/json
### Mock
GET http://localhost:4005/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$top=2
    &$count=true
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked
#    &$filter=BusinessPartner%20eq%20'1000038'
Accept: application/json

###
GET http://localhost:4005/odata/v4/API_BUSINESS_PARTNER/A_CustomerSalesAreaText
    ?$top=10
    &$count=true
Accept: application/json
