###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$top=10
APIKey: {{$dotenv apiKey}}
Accept: application/json
###
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_CustomerSalesAreaText/$count
APIKey: {{$dotenv apiKey}}
### Sample request to the api.sap.com Sandbox
GET {{$dotenv s4hanaSandbox}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$top=10
    &$inlinecount=allpages
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked
    #&$filter=Customer ne ''
    &$filter=BusinessPartner eq '1000038'
APIKey: {{$dotenv apiKey}}
Accept: application/json
### Real S/4HANA Cloud System
GET {{$dotenv s4hana}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$top=10
    &$inlinecount=allpages
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json
###
GET {{$dotenv s4hana}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_CustomerSalesAreaText
    ?$top=10
    &$inlinecount=allpages
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
Accept: application/json

### Get CSRF Token
# @name fetchCSRF
HEAD {{$dotenv s4hana}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
X-CSRF-Token: fetch
###
@csrfToken = {{fetchCSRF.response.headers.x-csrf-token}}

### Create Business Partner
POST {{$dotenv s4hana}}/sap/opu/odata/sap/API_BUSINESS_PARTNER/A_BusinessPartner
Authorization: Basic {{$dotenv username}}:{{$dotenv password}}
X-CSRF-Token: {{csrfToken}}
Accept: application/json
Content-Type: application/json

{
    "BusinessPartnerCategory": "2",
    "OrganizationBPName1": "Computerservice Wolf"
}
### Mock
GET http://localhost:4004/odata/v2/api-business-partner/A_BusinessPartner
    ?$top=10
    &$inlinecount=allpages
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked
    #&$filter=Customer ne ''
    #&$filter=BusinessPartner eq '1000038'
Accept: application/json

### Mock
GET http://localhost:4004/odata/v4/api-business-partner/A_BusinessPartner
    ?$top=2
    &$count=true
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked
#    &$filter=BusinessPartner%20eq%20'1000038'
Accept: application/json

###
GET http://localhost:4004/odata/v4/api-business-partner/A_CustomerSalesAreaText
    ?$top=1
    &$count=true
Accept: application/json
