###
GET http://localhost:4004/odata/v4/event/$metadata
###
POST http://localhost:4004/odata/v4/event/bpChanged
Content-Type: application/json

{
    "BusinessPartner": "1000038"
}
###
POST http://localhost:4004/odata/v4/event/bpChanged
Content-Type: application/json

{
    "BusinessPartner": "1000040"
}
