###
GET http://localhost:4004/odata/v4/replication/$metadata
###
GET http://localhost:4004/odata/v4/replication/BusinessPartner
    ?$count=true
Accept: application/json
###
POST http://localhost:4004/odata/v4/replication/loadBusinessPartner
Content-Type: application/json

{
    "BlockSize": 2
}
###
POST http://localhost:4004/odata/v4/replication/deleteAllBusinessPartners
Content-Type: application/json

{}
