### Read replicated entities
GET http://localhost:4004/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$count=true
    &$top=10
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked,source
    &$expand=to_Customer($expand=to_CustomerSalesArea($expand=to_SalesAreaText))
Accept: application/json
Authorization: Basic alice:
###
GET http://localhost:4004/odata/v4/API_BUSINESS_PARTNER/A_BusinessPartner
    ?$count=true
    &$top=10
    &$select=BusinessPartner,BusinessPartnerFullName,BusinessPartnerIsBlocked,source
    &$expand=to_Customer($expand=to_CustomerSalesArea($expand=to_SalesAreaText))
Accept: application/json
Authorization: Basic bob:
###
GET http://localhost:4004/odata/v4/API_BUSINESS_PARTNER/A_CustomerSalesAreaText
    ?$count=true
    &$top=10
    &$orderby=Customer
Accept: application/json
Authorization: Basic alice:
