###
GET http://localhost:4004/odata/v4/replication/
Authorization: Basic alice:
###
GET http://localhost:4004/odata/v4/replication/$metadata
Authorization: Basic alice:
### delete all replicated entities
POST http://localhost:4004/odata/v4/replication/deleteAllReplicatedEntities
Content-Type: application/json
Authorization: Basic alice:

{}
### Replicate entities from S4HANA_DEV to the local database
POST http://localhost:4004/odata/v4/replication/loadEntitiesFromS4
Content-Type: application/json
Authorization: Basic alice:

{
    "Destination": "S4HANA_DEV",
    "blockSize": {{$dotenv blockSize}},
    "maxCount": {{$dotenv maxCount}}
}
### Replicate entities from S4HANA to the local database
POST http://localhost:4004/odata/v4/replication/loadEntitiesFromS4
Content-Type: application/json
Authorization: Basic alice:

{
    "Destination": "S4HANA",
    "blockSize": {{$dotenv blockSize}},
    "maxCount": {{$dotenv maxCount}}
}
